### ISSUE TITLE
任意: イベントプログラム原稿確認依頼

### ISSUE THREAD

**Issue by yhirano55** [railsdm/2019#33]
イベント当日に配布する冊子を制作しています。以下にPDFがありますので、ご確認ください。

https://drive.google.com/file/d/1SneFfmG5joWfqzrhUPPxui2-Cwk75jLF/view?usp=sharing

1. 掲載枠の都合で日英併記できない場合は、日本語を優先しています。
2. Jeremyが読んだときにわかるよう、タイトルだけは必ず日英併記するようにしています。
3. 日本語タイトルがない場合は、運営の方でアレンジしましたが、問題あれば修正のご指摘をお願いします。
4. 本文やタイトルの大幅な変更はご遠慮ください。

なお、任意確認なので、変更リクエストがある場合のみご指摘くださいませ。

締切: 3月3日（日）19:00まで

**Comment by yhirano55** [comment]
上記ご確認をお願いいたします:

@takahashim, @284km, @aeroastro, @amatsuda, @banyan, @emorima, @f440, @fujimura, @gotchane, @hanachin, @hokaccha, @hsbt, @idesaku, @itkrt2y, @joker1007, @k0kubun, @katorie, @kei-p, @knu, @koic, @koichiro, @kokuyouwind, @komagata, @kyuden, @m-nakamura145, @masa-iwasaki, @moro, @Morred, @mrkn, @mtsmfm, @nay, @onk, @ota42y, @owlworks, @pipopotamasu, @r7kamura, @radioboo, @risacan, @rlho, @rust, @ryopeko, @siman-man, @sinamon129, @sinsoku, @taiki-t, @TakatoshiMaeda, @takkanm, @taogawa, @tawachan, @ujihisa

**Comment by yhirano55** [comment]
上記ご確認お願いいたします:

@unak, @upinetree, @ursm, @willnet, @y-yagi, @yahonda, @yancya, @yasaichi, @yoshiori, @yoshuki, @youchan, @yui-knk

cc: @okuramasafumi

**Comment by hsbt** [comment]
確認しました。書籍面白いですね。

**Comment by koic** [comment]
確認しました。私の挙げた Extreme Programming は初版に対して2版は全編リライトされており、私が選択したのは Kent Beck 単名の初版の方でした。初版と2版を分けた書き方にしても細かい点になってしまいますので、ざっくりした修正だと以下になります。

```diff
-『エクストリームプログラミング』Kent Beck, Cynthia Andres
+『エクストリームプログラミング』Kent Beck
```

**Comment by yhirano55** [comment]
@koic ありがとうございます。修正しておきます。

**Comment by yoshuki** [comment]
確認しました。③なのですが、3人での共著だったので、私の追記をお願いします。

**Comment by yhirano55** [comment]
@yoshuki すみません、変更したいテキストのdiffを書いていただけるとありがたいです :bow:

**Comment by yoshuki** [comment]
あわわ、失礼しました。
```diff
-③『Ruby on Rails 携帯サイト開発技法』伊藤 祐策, 富田 陽介
+③『Ruby on Rails 携帯サイト開発技法』伊藤 祐策, 富田 陽介, 三上 喜之
```
よろしくお願いします！

**Comment by youchan** [comment]
確認しました。3冊に技術書あんまり思いつかないなーって思っていたんだけど、そういえば「はるみのプログラミングレッスン」があったの思いだしました。(別に直さなくていいです)

**Comment by yhirano55** [comment]
@koic @yoshuki 修正しましたのでお時間があるときにでもご確認くださいませ。

https://drive.google.com/file/d/1SneFfmG5joWfqzrhUPPxui2-Cwk75jLF/view?usp=sharing

**Comment by koic** [comment]
確認しました。ご対応ありがとうございます。

他に気が付いた点のですが What does Ruby on Rails mean to you? に記されている kamipo さんの漢字姓が上薗でなく神薗になっております。以下参考まで。
https://www.ruby.or.jp/rubyprize2017/interview.html

**Comment by yhirano55** [comment]
おおお、まずい。すぐ直します。ありがとうございます。

**Comment by youchan** [comment]
> 神薗になっております

ある意味合っているのでは！？

**Comment by itkrt2y** [comment]
@yhirano55 話すことが当初の予定から少々変わりそうなので、すみませんが以下2行の削除をお願いします 🙏 

```diff
- 話すこと : ESNext, Virtual DOM, Performance, PWA, Web Components
- 話さないこと : React/Vue/Angular のどれを使うべき?
```

**Comment by yhirano55** [comment]
@itkrt2y 対応しました [*](https://drive.google.com/file/d/1SneFfmG5joWfqzrhUPPxui2-Cwk75jLF/view)

**Comment by yhirano55** [comment]
@Takatoshi-Maeda さん、ご確認お願いします。usernameが変わっていてミスってました。失礼しました。

**Comment by takatoshi-maeda** [comment]
確認しました！ ややこしい変更失礼しました :bow:

**Comment by sinsoku** [comment]
@yhirano55 pdfに記載されている画像をGitHubのアイコンに変更頂いても良いでしょうか？railsdmのwebページが猫だったので、同じ方が良いかなーと

**Comment by yhirano55** [comment]
@sinsoku わかりました。のちほど変更しておきます。

**Comment by yhirano55** [comment]
期限を過ぎたのでCloseします。皆様ありがとうございました。
