### ISSUE TITLE
コメント寄稿依頼: What does Ruby on Rails mean to you?

### ISSUE THREAD

**Issue by yhirano55** [railsdm/2019#36]
現在、参加者全員に配布するイベント用冊子を制作してまして、「What does Ruby on Rails mean to you?（あなたにとって、Ruby on Railsとは何か?）」という質問に対して、100文字以内（英語の場合は200文字）のコメントをいただけたら幸いです。

以下の23ページをご参照くださいませ。

https://drive.google.com/file/d/1SneFfmG5joWfqzrhUPPxui2-Cwk75jLF/view

以下は入稿フォームです。

https://docs.google.com/forms/d/e/1FAIpQLSfvhr6gA5oQbaFctKltByodnVJuiDsMIshQG0kzTU-RpwPVgA/viewform

入稿期限: 3月10日（日）23:59

**Comment by yhirano55** [comment]
褒め称えたいという趣旨ではないので、さまざまな視点から、多くのプログラマーにとっての、Ruby on Railsとは何か、という実態を探れたらと思っております。お手数おかけしますが、ご寄稿をお願いできますか? 

@takahashim, @onk, @takkanm, @willnet, @joker1007, @nay, @koic, @r7kamura, @moro, @yasaichi, @rlho, @risacan

（rlho, risacan にはDMでの連絡と重複していますが念のためこちらにも記載しました）

**Comment by yhirano55** [comment]
本日はおやすみですので明日また改めてDMでお願いさせていただきますが、もし本依頼について「OK」という方は、 👍 をいただけますと幸いです（その際はDMは割愛いたします）

**Comment by yhirano55** [comment]
@takahashim さっそくのご寄稿ありがとうございました :pray:

**Comment by yhirano55** [comment]
@amatsuda DMでもお願いいたしましたがこちらお願いします。

**Comment by takahashim** [comment]
@yhirano55 とりあえず書いてみましたが、100文字だとちょっと短そう？と思いました（とはいえ1,000文字書いてもいいよと言われてももりもり書けるかどうかは怪しいですが…）。

**Comment by yhirano55** [comment]
@takahashim たしかに日本語だと100文字ですが、英語だと200文字入るので調整します。ありがとうございます。

**Comment by moro** [comment]
送りました!! 短くしようと意気込んでたら70文字くらいにまとめてしまった(ので、ちょっと伸ばしましたw)

**Comment by yhirano55** [comment]
@moro いまちょうどDMしようとしていたところでしたが、先にご寄稿いただきありがとうございます！

**Comment by koic** [comment]
日本語100文字で書いてみたものを d で送付いたしました。

**Comment by nay** [comment]
フォームへ送信doneです！ 🙏

**Comment by yhirano55** [comment]
ご寄稿ありがとうございました🙏
